export const VehicleData = [
    {
        VIN: "VIN 100",
        licensePlate: "ABC123",
        make: "Toyota",
        model: "Camry",
        type: "Sedan",
        date: "2024-12-25",
        milesDriven: 150,
    },
    {
        VIN: "VIN 101",
        licensePlate: "DEF456",
        make: "Honda",
        model: "Accord",
        type: "Sedan",
        date: "2024-08-23",
        milesDriven: 200,
    },
    {
        VIN: "VIN 102",
        licensePlate: "GHI789",
        make: "Ford",
        model: "F-150",
        type: "Truck",
        date: "2024-08-23",
        milesDriven: 300,
    },
    {
        VIN: "VIN 104",
        licensePlate: "BH8019",
        make: "Ford",
        model: "Mustang",
        type: "Muscle-Car",
        date: "2024-08-23",
        milesDriven: 240,
    },
    {
        VIN: "VIN 107",
        licensePlate: "KA1234",
        make: "Mitsubishi",
        model: "Lancer-Evolution",
        type: "Sedan",
        date: "2024-08-23",
        milesDriven: 300,
    },
    {
        VIN: "VIN 108",
        licensePlate: "BJ1434",
        make: "Opel",
        model: "Speedster",
        type: "Hatchback",
        date: "2024-08-23",
        milesDriven: 300,
    },
    {
        VIN: "VIN 112",
        licensePlate: "AP8745",
        make: "Benz",
        model: "CLK-GTR",
        type: "Sedan",
        date: "2024-08-23",
        milesDriven: 600,
    },
    {
        VIN: "VIN 113",
        licensePlate: "KL6542",
        make: "Konigsegg",
        model: "Jetta",
        type: "Sedan",
        date: "2024-08-24",
        milesDriven: 400,
    },
    {
        VIN: "VIN 114",
        licensePlate: "BH2546",
        make: "Audi",
        model: "Q8",
        type: "SUV",
        date: "2024-08-25",
        milesDriven: 700,
    },
    {
        VIN: "VIN 120",
        licensePlate: "MH7684",
        make: "Mahindra",
        model: "Xylo",
        type: "SUV",
        date: "2024-08-28",
        milesDriven: 900,
    },
];